=== dfvips/JavaWebStudy/WebContent/dtd/chapter2-1.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT team (student+)>
<!ELEMENT student (s_id,s_name,s_sgender,s_age,s_department)>
<!ELEMENT s_id (#PCDATA)>
<!ELEMENT s_name (#PCDATA)>
<!ELEMENT s_sgender (#PCDATA)>
<!ELEMENT s_age (#PCDATA)>
<!ELEMENT s_department (#PCDATA)>
<!ATTLIST student role (技术总监|财务总监|生产总监|采购总监|销售总监) "技术总监">

=== dfvips/JavaWebStudy/WebContent/xml/chapter2-1.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE note SYSTEM "../dtd/chapter2-1.dtd">
<team>
<student role="技术总监">
<s_id>2018001</s_id>
<s_name>张三</s_name>
<s_sgender>男</s_sgender>
<s_age>19</s_age>
<s_department>计算机工程系</s_department>
</student>
<student role="财务总监">
<s_id>2018002</s_id>
<s_name>李四</s_name>
<s_sgender>女</s_sgender>
<s_age>19</s_age>
<s_department>工商管理系</s_department>
</student>
<student role="生产总监">
<s_id>2018003</s_id>
<s_name>王五</s_name>
<s_sgender>男</s_sgender>
<s_age>20</s_age>
<s_department>电子工程系</s_department>
</student>
<student role="采购总监">
<s_id>2018004</s_id>
<s_name>赵六</s_name>
<s_sgender>女</s_sgender>
<s_age>18</s_age>
<s_department>计算机工程系</s_department>
</student>
<student role="销售总监">
<s_id>2018005</s_id>
<s_name>孙七</s_name>
<s_sgender>男</s_sgender>
<s_age>20</s_age>
<s_department>工商管理系</s_department>
</student>
</team>
